# =============================================================================
# models/forecast.py — Forecast ORM Model
# =============================================================================
# PURPOSE: Stores AI-generated predictions for energy consumption, occupancy,
# temperature, and other variables. Forecasts are the output of the ML pipeline
# (XGBoost, LightGBM, Prophet, etc.) and are used by the optimization engine
# to generate actionable recommendations.
#
# Each forecast is tied to a specific zone and a future timestamp, allowing
# the dashboard to display predicted vs. actual values and measure AI accuracy.
#
# FORECAST TYPES (examples):
#   - "energy_consumption" → predicted kWh for a zone
#   - "occupancy"          → predicted number of occupants
#   - "temperature"        → predicted ambient temperature
#   - "hvac_load"          → predicted HVAC energy demand
#
# TABLE: forecasts
# COLUMNS: id (UUID PK), zone_id (FK), forecast_type, predicted_value,
#          forecast_time, created_at
# =============================================================================

import uuid
from datetime import datetime

from sqlalchemy import String, Float, ForeignKey, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Forecast(Base):
    """
    An AI-generated prediction for a specific zone and future time.
    """
    __tablename__ = "forecasts"

    # -------------------------------------------------------------------------
    # PRIMARY KEY
    # -------------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        comment="Unique forecast identifier"
    )

    # -------------------------------------------------------------------------
    # FOREIGN KEY — Which zone this forecast applies to
    # -------------------------------------------------------------------------
    zone_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("zones.id", ondelete="CASCADE"),
        nullable=False,
        comment="The zone this forecast applies to"
    )

    # -------------------------------------------------------------------------
    # FORECAST DATA
    # -------------------------------------------------------------------------
    forecast_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Type of prediction: energy_consumption, occupancy, temperature, hvac_load"
    )
    predicted_value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="The predicted numeric value (units depend on forecast_type)"
    )
    forecast_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        comment="The future timestamp this prediction is for"
    )

    # -------------------------------------------------------------------------
    # METADATA
    # -------------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        comment="When this forecast was generated by the AI engine"
    )

    # -------------------------------------------------------------------------
    # RELATIONSHIPS
    # -------------------------------------------------------------------------
    zone = relationship("Zone", back_populates="forecasts")
