# =============================================================================
# schemas/energy.py — Analytics Response Schemas
# =============================================================================
# PURPOSE: Define response schemas for the analytics/dashboard endpoints.
# These endpoints aggregate time-series data for visualization.
#
# ENDPOINTS USING THESE SCHEMAS:
#   GET /api/v1/buildings/{id}/energy-summary     → EnergySummary (response)
#   GET /api/v1/buildings/{id}/carbon-emissions    → CarbonEmissions (response)
#   GET /api/v1/anomalies?building_id=             → list[AnomalyRecord] (response)
# =============================================================================

from datetime import datetime

from pydantic import BaseModel, Field


class EnergyBucket(BaseModel):
    """
    A single time bucket in the energy summary.
    Represents aggregated energy data for one time period (e.g., 1 hour).
    Generated by TimescaleDB's time_bucket() function.
    """
    bucket: datetime = Field(..., description="Start of the time bucket")
    total_kwh: float = Field(..., description="Total energy consumed in this bucket (kWh)")
    avg_kwh: float = Field(..., description="Average energy per reading in this bucket")
    peak_kwh: float = Field(..., description="Maximum single reading in this bucket")


class EnergySummary(BaseModel):
    """
    Response for GET /api/v1/buildings/{id}/energy-summary.
    Contains a list of time-bucketed energy aggregations.
    """
    building_id: str = Field(..., description="Building identifier")
    start: datetime = Field(..., description="Query start time")
    end: datetime = Field(..., description="Query end time")
    buckets: list[EnergyBucket] = Field(..., description="Time-bucketed energy data")
    total_kwh: float = Field(..., description="Total energy over the entire period")


class CarbonBucket(BaseModel):
    """
    A single time bucket in the carbon emissions report.
    Carbon is estimated from energy consumption using a configurable emission factor.
    """
    bucket: datetime = Field(..., description="Start of the time bucket")
    total_kwh: float = Field(..., description="Total energy in this bucket")
    carbon_kg: float = Field(..., description="Estimated CO2 emissions in kg")


class CarbonEmissions(BaseModel):
    """
    Response for GET /api/v1/buildings/{id}/carbon-emissions.
    Converts energy data to estimated CO2 emissions using an emission factor.
    """
    building_id: str = Field(..., description="Building identifier")
    start: datetime = Field(..., description="Query start time")
    end: datetime = Field(..., description="Query end time")
    emission_factor_kg_per_kwh: float = Field(
        ...,
        description="CO2 emission factor used for calculation (kg CO2 per kWh)"
    )
    buckets: list[CarbonBucket] = Field(..., description="Time-bucketed emissions data")
    total_carbon_kg: float = Field(..., description="Total estimated CO2 over the period (kg)")


class AnomalyRecord(BaseModel):
    """
    A detected anomaly in sensor or energy data.
    Used by GET /api/v1/anomalies to report unusual readings.
    """
    id: str = Field(..., description="Anomaly identifier")
    building_id: str = Field(..., description="Building where anomaly occurred")
    zone_id: str | None = Field(None, description="Zone (if zone-specific)")
    timestamp: datetime = Field(..., description="When the anomaly was detected")
    sensor_type: str = Field(..., description="Type of sensor that triggered the anomaly")
    expected_value: float = Field(..., description="Expected/normal value")
    actual_value: float = Field(..., description="Actual observed value")
    severity: str = Field(..., description="Anomaly severity: low, medium, high, critical")
    description: str = Field(..., description="Human-readable explanation of the anomaly")
