# =============================================================================
# schemas/recommendation.py — Recommendation Request/Response Schemas
# =============================================================================
# PURPOSE: Define Pydantic models for AI recommendation CRUD operations.
#
# Recommendations follow a lifecycle: pending → approved → applied (or rejected).
# The PATCH endpoint allows updating the status (approve/apply/reject).
#
# ENDPOINTS USING THESE SCHEMAS:
#   POST  /api/v1/recommendations       → RecommendationCreate (request body)
#   PATCH /api/v1/recommendations/{id}   → RecommendationUpdate (request body)
#   GET   /api/v1/recommendations        → list[RecommendationRead] (response)
# =============================================================================

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RecommendationCreate(BaseModel):
    """
    Request body for inserting a new AI recommendation.
    Typically called by the optimization engine after analyzing forecasts.
    """
    zone_id: UUID = Field(..., description="The zone this recommendation targets")
    recommendation_type: str = Field(
        ...,
        max_length=50,
        description="Action type: hvac_setpoint, lighting_level, hvac_schedule, ventilation_rate"
    )
    value: float = Field(
        ...,
        description="Recommended value (e.g., 22.5 for °C setpoint, 75 for 75% lighting)"
    )


class RecommendationUpdate(BaseModel):
    """
    Request body for updating a recommendation's status (PATCH).
    Used by facility managers and technicians to approve, apply, or reject.
    """
    status: str = Field(
        ...,
        description="New status: approved, applied, or rejected"
    )
    applied_at: datetime | None = Field(
        None,
        description="Timestamp when the recommendation was applied to BMS (auto-set if status='applied')"
    )


class RecommendationRead(BaseModel):
    """
    Full recommendation representation returned in API responses.
    """
    id: UUID = Field(..., description="Unique recommendation identifier")
    zone_id: UUID = Field(..., description="Target zone ID")
    recommendation_type: str = Field(..., description="Action type")
    value: float = Field(..., description="Recommended value")
    status: str = Field(..., description="Current lifecycle status")
    created_at: datetime = Field(..., description="When generated by AI engine")
    applied_at: datetime | None = Field(None, description="When applied (null if not yet)")

    model_config = ConfigDict(from_attributes=True)
